Repository pedrommcarrasco/Brooklyn, pull requests merged in 2019-03, with the labels that each got.

#21 [wip] Isolate animations
  Brooklyn/Resources/appleBits.mp4
  Brooklyn/Resources/doodle.mp4
Labels: enhancement

#29 2.0.0 Improvements
  .travis.yml
  Brooklyn.xcodeproj/project.pbxproj
  Brooklyn/Contexts/Preferences/AnimationCellView.swift
  Brooklyn/Contexts/Preferences/PreferencesWindowController.swift
  Brooklyn/Contexts/Preferences/PreferencesWindowController.xib
  Brooklyn/Enumerations/Animation.swift
Labels: enhancement, release, technical enhancement

#31 Brooklyn 2.0.1
  Brooklyn/Contexts/Preferences/PreferencesWindowController.swift
  Brooklyn/Contexts/Preferences/PreferencesWindowController.xib
  Brooklyn/Info.plist
Labels: bug, release
